### ISSUE TITLE
Data Visualization with Python

### ISSUE THREAD

**Issue by pranalibose** [HydPy/HydPy-meetups#86]
**Title of the talk/workshop**
Data Storytelling in Python

**Abstract of the talk/workshop**
Using Python libraries to analyse data

**Category of the talk/workshop**
Exploratory Data Analysis

**Duration (including Q&A)**
30 mins

**Level of Audience**
Beginner/Intermediate

**Speaker Bio**
1. Machine Learning Engineer with 7 years of experience working in different domains. Core Skills: Python, Data Manipulation and Visualisation, Data Science and Machine Learning mainly supervised and unsupervised. 
2. DBS
3. pranalibose01@gmail.com
4. 7 years

**Prerequisites(if any)**

**Alternate proposal**

**Title of the talk/workshop**
Pandas Optimization Hacks

**Abstract of the talk/workshop**
Pandas different optimization techniques

**Category of the talk/workshop**
Python Optimization

**Details**
Intend to cover the below pandas optimization techniques:
1. Memory Optimization
2. Vectorization
3. Chunking Method
4. Filter Optimization
5. Profiling

**Comment by bpkapkar** [comment]
Thank you  @pranalibose for submitting your proposal. We have reviewed it and would like to learn more details. Additionally, we are interested in having you cover some advanced topics on the same subject to provide deeper insights for the audience. Please let us know any specific aspects you'd like to explore, so we can ensure the audience gains valuable new knowledge.

**Comment by pranalibose** [comment]
Sure @bpkapkar Let me get back to you with more details by today evening.

**Comment by bpkapkar** [comment]
@pranalibose Thank you for your submission and interest in speaking at our upcoming event. After reviewing the details and topics, it seems they cover more basic concepts. Since we aim to provide our audience with a mix of foundational and advanced content, I’d kindly request you to either submit an updated talk that deeps dive into more advanced topics or frameworks.

Alternatively, you’re welcome to submit a new proposal on other topics as well, if that better aligns with your expertise or interest.
This will help us ensure that the session provides added value for attendees looking to expand their knowledge.

**Comment by pranalibose** [comment]
@bpkapkar I have added an alternate proposal. Please review.

**Comment by bpkapkar** [comment]
Thanks  @pranalibose for your submission. However, we are unable to view it at the moment. In the meantime, I will go ahead and close this issue, as you’ve opted to submit a new proposal.
We’ll be happy to review it once you submit the updated talk.
